openapi: 3.0.2
info:
  description: Календарь
  title: Calendar-service API
  version: 0.0.1
components:
  schemas:
    Profile:
      type: object
      description: Профиль пользователя
      properties:
        login:
          type: string
          description: Логин пользователя
        email:
          type: string
          description: email пользователя
        phone:
          type: string
          description: Номер телефона
        active:
          type: boolean
          description: Признак активного пользователя
        firstName:
          type: string
          description: Имя
        lastName:
          type: string
          description: Фамилия
        middleName:
          type: string
          description: Отчество
    Pagable:
      type: object
      description: Параметры пагинации и фильтрации
      properties:
        pageNo:
          type: integer
          format: int32
          description: Страница
        pageSize:
          type: integer
          format: int32
          description: Размер страницы
        direction:
          type: string
          description: Направление
        offset:
          type: integer
          format: int32
          description: Указатель на страницу
        limit:
          type: integer
          format: int32
          description: Размер страницы
        filter:
          description: Быстрый фильтр
          type: string
    User:
      type: object
      description: Метаданные пользователя
      properties:
        login:
          type: string
          description: Логин
        FIO:
          type: string
          description: Полное имя пользователя
    UserAuth:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
    Organization:
      type: object
      description: Метаданные организации
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          description: Наименование
        email:
          type: string
          description: email организации
    OrganizationCreate:
      type: object
      properties:
        name:
          type: string
          description: Наименование
        email:
          type: string
          description: email организации
    ScheduleCreate:
      type: object
      properties:
        id:
          type: integer
          format: int64
        workDays:
          type: integer
          description: Диапазон рабочих дней
        weekendDays:
          type: integer
          description: Диапазон не рабочих дней
        title:
          type: string
          description: Название
        ownerHoliday:
          type: array
          description: Выходные дни, установленные владельцем
          items:
            type: string
            format: date
        schedule:
          type: array
          description: Сетка расписания
          items:
            $ref: '#/components/schemas/ScheduleElement'
    ScheduleGenerate:
      type: object
      properties:
        workDays:
          type: integer
          format: int32
        withOfficialHolidays:
          type: boolean
        title:
          type: string
        startDate:
          type: string
        periodOfSchedule:
          type: string
        holidays:
          type: array
          items:
            type: string
            format: date
        managers:
          type: array
          items:
            type: string
        users:
          type: array
          items:
            type: string
    Schedule:
      type: object
      description: Расписание
      properties:
        id:
          type: integer
          format: int64
        workDays:
          type: integer
          description: Диапазон рабочих дней
        weekendDays:
          type: integer
          description: Диапазон не рабочих дней
        createdBy:
          type: string
          description: Создатель
        created:
          type: string
          format: date
          description: Дата создания
        updatedBy:
          type: string
          description: Обновлено
        update:
          type: string
          format: date
          description: Дата обновления
        ownerHoliday:
          type: array
          description: Выходные дни, установленные владельцем
          items:
            type: string
            format: date
        schedule:
          type: array
          description: Сетка расписания
          items:
            $ref: '#/components/schemas/ScheduleElement'
    ScheduleElement:
      type: object
      properties:
        user:
          type: string
          description: Пользователь, член команды
        workDays:
          type: array
          items:
            type: string
            format: date
    ScheduleShort:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          description: Наименование
        workDays:
          type: integer
          description: Диапазон рабочих дней
        weekendDays:
          type: integer
          description: Диапазон не рабочих дней
    ScheduleList:
      type: object
      description: Список расписаний
      properties:
        pageNo:
          type: integer
          description: Номер страницы
        pageSize:
          type: integer
          description: Размер страницы
        size:
          type: integer
          format: int64
          description: Общее количество календарей
        schedules:
          $ref: '#/components/schemas/ScheduleShort'
    Calendar:
      type: object
      description: Календарь
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          description: Наименование
        owner:
          type: object
          description: Логин владельца
        organization:
          $ref: '#/components/schemas/Organization'
          description: Организация, привязанная к календарю
        schedules:
          type: array
          $ref: '#/components/schemas/ScheduleShort'
        createdBy:
          type: string
          description: Создатель
        created:
          type: string
          format: date
          description: Дата создания
        updatedBy:
          type: string
          description: Обновлено
        update:
          type: string
          format: date
          description: Дата обновления
    CalendarCreate:
      type: object
      properties:
        title:
          type: string
          description: Наименование
        ownerLogin:
          type: string
        organizationId:
          type: integer
          format: int64
          description: Организация
    CalendarShort:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          description: Наименование
        organization:
          description: Организация
          $ref: '#/components/schemas/Organization'
    CalendarList:
      type: object
      description: Список календарей пользователя
      properties:
        pageNo:
          type: integer
          description: Номер страницы
        pageSize:
          type: integer
          description: Размер страницы
        size:
          type: integer
          format: int64
          description: Общее количество календарей
        calendars:
          type: array
          items:
            $ref: '#/components/schemas/CalendarShort'
    Task:
      type: object
      description: Задача
      properties:
        text:
          type: string
          description: Описание
        done:
          type: boolean
          description: Завершена
        userLogin:
          type: string
          description: Исполнитель
        userControl:
          type: string
          description: Проверяющий
        approved:
          type: boolean
          description: Проверяющий проверил задачу
        approvingComment:
          type: string
          description: Комментарий проверяющего
        date:
          type: string
          format: date
          description: Дата задачи
        deadline:
          type: string
          format: date
          description: Срок
        completeTask:
          type: string
          format: date
          description: Дата завершения
        order:
          type: integer
          format: int32
          description: Очередность в группе
        createdBy:
          type: string
          description: Создатель
        created:
          type: string
          format: date
          description: Дата создания
        updatedBy:
          type: string
          description: Обновлено
        update:
          type: string
          format: date
          description: Дата обновления
    TaskCreate:
      type: object
      description: Задача
      properties:
        text:
          type: string
          description: Описание
        userLogin:
          type: string
          description: Исполнитель
        userControl:
          type: string
          description: Проверяющий
        date:
          type: string
          format: date
          description: Дата задачи
        deadline:
          type: string
          format: date
          description: Срок
        groupUuid:
          type: string
          description: id группы
        order:
          type: integer
          format: int32
          description: Очередность в группе
        personal:
          type: boolean
          description: Личная задача
        calendarId:
          type: integer
          format: int64
          description: id календаря
        scheduleId:
          type: integer
          format: int64
          description: id расписания
    TaskComplete:
      type: object
      description: Параметры завершенной задачи
      properties:
        completeText:
          type: string
          description: Результат
    TaskApprove:
      type: object
      description: Параметры проверки задачи
      properties:
        approved:
          type: boolean
          description: Проверяющий проверил задачу
        approvingComment:
          type: string
          description: Комментарий проверяющего
    Error:
      type: object
      properties:
        timestamp:
          type: string
          description: Время исключения
        message:
          type: string
          description: Описание ошибки
        serviceName:
          type: string
          description: Имя недоступного интеграционного сервиса
